name: Build Godot Project

on:
  push:
    tags:
      - v0.**

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    env:
        VERSION: ${{ GITHUB_REF_NAME || 'devel' }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: ltdt-${{ matrix.platform }}-${{ env.VERSION }}.zip
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ltdt-${{ matrix.platform }}-${{ env.VERSION }}.zip
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
