name: Run Static Checks

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run All Tests
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: run test script
        run: bash run_tests.sh
