name: Run Static Checks

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: run_all_tests
    run-name: tests on ${{ github.ref_name || 'unknown' }} by @${{ github.actor }}
    steps:
      - uses: actions/checkout@v3
          with:
            lfs: true
      - name: run test script
        run: bash run_tests.sh
